### ISSUE TITLE
Error "SIGSYS: bad system call" in Termux Linux environment for Android

### ISSUE THREAD

**Issue by 7RUSHI** [hickford/git-credential-oauth#34]
```
 ~ $ git-credential-oauth configure
SIGSYS: bad system call
PC=0x12850 m=0 sigcode=1

goroutine 1 [syscall]:
syscall.Syscall6(0x40000c0330?, 0x27?, 0x27?, 0x40000c0360?, 0x0?, 0x4f?, 0xffffffffffffff9c?)
        /home/linuxbrew/.linuxbrew/Cellar/go/1.20.7/libexec/src/syscall/syscall_linux.go:91 +0x2c fp=0x400009a8d0 sp=0x400009a840 pc=0x8268c
syscall.faccessat2(0x40000c0330?, {0x40000c0330?, 0x7d62dcabc8?}, 0x1, 0xc0?)
        /home/linuxbrew/.linuxbrew/Cellar/go/1.20.7/libexec/src/syscall/zsyscall_linux_arm64.go:33 +0x84 fp=0x400009a940 sp=0x400009a8d0 pc=0x7fe44
syscall.Faccessat(0x40000c0330?, {0x40000c0330, 0x27}, 0x1, 0x200)
        /home/linuxbrew/.linuxbrew/Cellar/go/1.20.7/libexec/src/syscall/syscall_linux.go:167 +0x3c fp=0x400009aa30 sp=0x400009a940 pc=0x7e4fc
internal/syscall/unix.Eaccess(...)
        /home/linuxbrew/.linuxbrew/Cellar/go/1.20.7/libexec/src/internal/syscall/unix/eaccess_linux.go:10
os/exec.findExecutable({0x40000c0330, 0x27})
        /home/linuxbrew/.linuxbrew/Cellar/go/1.20.7/libexec/src/os/exec/lp_unix.go:31 +0x58 fp=0x400009aa80 sp=0x400009aa30 pc=0x226b18
os/exec.LookPath({0x2c9c3a, 0x3})
        /home/linuxbrew/.linuxbrew/Cellar/go/1.20.7/libexec/src/os/exec/lp_unix.go:71 +0x1b8 fp=0x400009ab20 sp=0x400009aa80 pc=0x226de8
main.main()
        /home/matthickford/git-credential-oauth/main.go:294 +0x15cc fp=0x400009af70 sp=0x400009ab20 pc=0x23f7fc
runtime.main()
        /home/linuxbrew/.linuxbrew/Cellar/go/1.20.7/libexec/src/runtime/proc.go:250 +0x200 fp=0x400009afd0 sp=0x400009af70 pc=0x45150
runtime.goexit()
        /home/linuxbrew/.linuxbrew/Cellar/go/1.20.7/libexec/src/runtime/asm_arm64.s:1172 +0x4 fp=0x400009afd0 sp=0x400009afd0 pc=0x72fc4

goroutine 2 [force gc (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        /home/linuxbrew/.linuxbrew/Cellar/go/1.20.7/libexec/src/runtime/proc.go:381 +0xe0 fp=0x4000042fa0 sp=0x4000042f80 pc=0x45560
runtime.goparkunlock(...)
        /home/linuxbrew/.linuxbrew/Cellar/go/1.20.7/libexec/src/runtime/proc.go:387
runtime.forcegchelper()
        /home/linuxbrew/.linuxbrew/Cellar/go/1.20.7/libexec/src/runtime/proc.go:305 +0xb0 fp=0x4000042fd0 sp=0x4000042fa0 pc=0x453b0
runtime.goexit()
        /home/linuxbrew/.linuxbrew/Cellar/go/1.20.7/libexec/src/runtime/asm_arm64.s:1172 +0x4 fp=0x4000042fd0 sp=0x4000042fd0 pc=0x72fc4
created by runtime.init.6
        /home/linuxbrew/.linuxbrew/Cellar/go/1.20.7/libexec/src/runtime/proc.go:293 +0x24

goroutine 3 [GC sweep wait]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        /home/linuxbrew/.linuxbrew/Cellar/go/1.20.7/libexec/src/runtime/proc.go:381 +0xe0 fp=0x4000043760 sp=0x4000043740 pc=0x45560
runtime.goparkunlock(...)
        /home/linuxbrew/.linuxbrew/Cellar/go/1.20.7/libexec/src/runtime/proc.go:387
runtime.bgsweep(0x0?)
        /home/linuxbrew/.linuxbrew/Cellar/go/1.20.7/libexec/src/runtime/mgcsweep.go:278 +0x98 fp=0x40000437b0 sp=0x4000043760 pc=0x320d8
runtime.gcenable.func1()
        /home/linuxbrew/.linuxbrew/Cellar/go/1.20.7/libexec/src/runtime/mgc.go:178 +0x28 fp=0x40000437d0 sp=0x40000437b0 pc=0x27418
runtime.goexit()
        /home/linuxbrew/.linuxbrew/Cellar/go/1.20.7/libexec/src/runtime/asm_arm64.s:1172 +0x4 fp=0x40000437d0 sp=0x40000437d0 pc=0x72fc4
created by runtime.gcenable
        /home/linuxbrew/.linuxbrew/Cellar/go/1.20.7/libexec/src/runtime/mgc.go:178 +0x6c

goroutine 4 [GC scavenge wait]:
runtime.gopark(0x4000062000?, 0x345910?, 0x1?, 0x0?, 0x0?)
        /home/linuxbrew/.linuxbrew/Cellar/go/1.20.7/libexec/src/runtime/proc.go:381 +0xe0 fp=0x4000043f50 sp=0x4000043f30 pc=0x45560
runtime.goparkunlock(...)
        /home/linuxbrew/.linuxbrew/Cellar/go/1.20.7/libexec/src/runtime/proc.go:387
runtime.(*scavengerState).park(0x4fffc0)
        /home/linuxbrew/.linuxbrew/Cellar/go/1.20.7/libexec/src/runtime/mgcscavenge.go:400 +0x5c fp=0x4000043f80 sp=0x4000043f50 pc=0x3006c
runtime.bgscavenge(0x0?)
        /home/linuxbrew/.linuxbrew/Cellar/go/1.20.7/libexec/src/runtime/mgcscavenge.go:628 +0x44 fp=0x4000043fb0 sp=0x4000043f80 pc=0x305a4
runtime.gcenable.func2()
        /home/linuxbrew/.linuxbrew/Cellar/go/1.20.7/libexec/src/runtime/mgc.go:179 +0x28 fp=0x4000043fd0 sp=0x4000043fb0 pc=0x273b8
runtime.goexit()
        /home/linuxbrew/.linuxbrew/Cellar/go/1.20.7/libexec/src/runtime/asm_arm64.s:1172 +0x4 fp=0x4000043fd0 sp=0x4000043fd0 pc=0x72fc4
created by runtime.gcenable
        /home/linuxbrew/.linuxbrew/Cellar/go/1.20.7/libexec/src/runtime/mgc.go:179 +0xac

goroutine 17 [finalizer wait]:
runtime.gopark(0x40000425a8?, 0x60000000024e98?, 0x28?, 0xa7?, 0x1?)
        /home/linuxbrew/.linuxbrew/Cellar/go/1.20.7/libexec/src/runtime/proc.go:381 +0xe0 fp=0x4000042580 sp=0x4000042560 pc=0x45560
runtime.runfinq()
        /home/linuxbrew/.linuxbrew/Cellar/go/1.20.7/libexec/src/runtime/mfinal.go:193 +0x100 fp=0x40000427d0 sp=0x4000042580 pc=0x264e0
runtime.goexit()
        /home/linuxbrew/.linuxbrew/Cellar/go/1.20.7/libexec/src/runtime/asm_arm64.s:1172 +0x4 fp=0x40000427d0 sp=0x40000427d0 pc=0x72fc4
created by runtime.createfing
        /home/linuxbrew/.linuxbrew/Cellar/go/1.20.7/libexec/src/runtime/mfinal.go:163 +0x80

r0      0xffffffffffffff9c
r1      0x40000c0390
r2      0x1
r3      0x200
r4      0x0
r5      0x0
r6      0x0
r7      0x1
r8      0x1b7
r9      0x2f7273752f73656c
r10     0x2e6d6f632f617461
r11     0x662f78756d726574
r12     0x7273752f73656c69
r13     0x7469672f6e69622f
r14     0x14
r15     0x56574f6f625a0a2f
r16     0x400009a3a0
r17     0x400009a9c0
r18     0x0
r19     0x1c
r20     0x400009a9c0
r21     0x40000f0818
r22     0xfffffffffffffff7
r23     0x8
r24     0xffffffffffffffa2
r25     0x36
r26     0x400009a7a0
r27     0x1
r28     0x40000021a0
r29     0x400009a7d8
lr      0x1280c
sp      0x400009a7e0
pc      0x12850
fault   0x0
~ $
```

**Comment by hickford** [comment]
Hi. Please could you describe your system and how you installed git-credential-oauth?

**Comment by 7RUSHI** [comment]
I have downloaded [git-credential-oauth_0.10.0_linux_arm64.tar.gz](https://github.com/hickford/git-credential-oauth/releases/download/v0.10.0/git-credential-oauth_0.10.0_linux_arm64.tar.gz) & installed it in [Termux](https://termux.dev/en/) Android Application. FYI My Mobile CPU Architecture is `AARCH64`.

**Comment by 7RUSHI** [comment]
Not Fixed

**Comment by hickford** [comment]
Sounds like the Termux Linux environment doesn't support the necessary system calls. You could try forking git-credential-oauth and removing all the system calls, but even if it worked, the application wouldn't be that useful.

I recommend you use [personal access tokens](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens) for Git authentication instead.

**Comment by romanovj** [comment]
not compiled for android abi, so you should install  it with go

```
go install github.com/hickford/git-credential-oauth@latest

~/go/bin/git-credential-oauth configure
configured successfully
```

**Comment by 7RUSHI** [comment]
> Sounds like the Termux Linux environment doesn't support the necessary system calls. You could try forking git-credential-oauth and removing all the system calls, but even if it worked, the application wouldn't be that useful.
> 
> I recommend you use [personal access tokens](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens) for Git authentication instead.

Okay Thanks, Yes I'm using PAT by encrypting with GNU Privacy Guard and a Bash shell script as Credential Manager to decrypt while Authentication.

**Comment by 7RUSHI** [comment]
> not compiled for android abi, so you should install it with go (in termux, not in proot)
> 
> ```
> go install github.com/hickford/git-credential-oauth@latest
> 
> ~/go/bin/git-credential-oauth configure
> configured successfully
> 
> cp ~/go/bin/git-credential-oauth $PREFIX/bin
> 
> git credential-oauth
> 
> OK
> ```
> 
> ```
> ldd $(which git-credential-oauth)
>         libdl.so => /system/lib64/libdl.so
>         libc.so => /data/data/com.termux/files/usr/lib/libc.so
>         ld-android.so => /system/lib64/ld-android.so
> ```

Okay Thanks, Will look into it.

**Comment by hickford** [comment]
@romanovj Is that the same as cross compiling `GOOS=android GOARCH=arm64 go build`? 

[git-credential-oauth_0.10.0_android_arm64.tar.gz](https://github.com/hickford/git-credential-oauth/files/12447443/git-credential-oauth_0.10.0_android_arm64.tar.gz)

**Comment by romanovj** [comment]
@hickford not the samr, but should be fine (statically linked  + abi android)

termux's clang
```
clang -v
clang version 16.0.6
Target: aarch64-unknown-linux-android24
Thread model: posix

```

**Comment by hickford** [comment]
Thanks. If that build functions usefully, I’ll add it to the regular release
